on: push
name: Run the AFK-Bot
jobs:
  join:
    name: Join the server
    runs-on: ubuntu-latest
    steps:
    - name: Start Afk-bot
      uses: Minionguyjpro/Afk-bot@v1.0.3
      with:
        ip: woopors.aternos.me
        name: AFKBOT
        port: 20131
        auto-night-skip: true
